

######################### Login Routes #########################

### User Login
# @name admin_jwt_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###
@token={{admin_jwt_login.response.body.access_token}}

### Get current user info
GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}

### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer {{token}}

######################### Products Routes #########################

### Get all products
GET http://localhost:3000/products
Authorization: Bearer {{token}}

### Get a product by ID
GET http://localhost:3000/products/by-id/83
Authorization: Bearer {{token}}

### Get a paginated products with filters
GET http://localhost:3000/products/paginated?minPrice=10&maxPrice=60
Authorization: Bearer {{token}}

### Create a new product
POST http://localhost:3000/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New Product",
  "description": "This is a new product",
  "price": 49.99,
  "categoryId": 1,
  "stock": 100,
  "sku": "SKU12445"
}

### Create a new variant
POST http://localhost:3000/products/variant
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New Product",
  "description": "This is a new product",
  "price": 49.99,
  "parentId": 1,
  "stock": 100,
  "attributes": {
    "size": "M",
    "color": "Red",
    "material": "Cotton"
  },
  "sku": "SKU123457"
}

### Update a product
PATCH http://localhost:3000/products/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Product Name",
  "price": 59.99
}

### Update a variant
PATCH http://localhost:3000/products/variant/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Variant Name",
  "price": 39.99
}

### Delete a product
DELETE http://localhost:3000/products/1
Authorization: Bearer {{token}}

######################### Categories Routes #########################

### Get all categories
GET http://localhost:3000/categories
Authorization: Bearer {{token}}

### Get a category by ID
GET http://localhost:3000/categories/by-id/1
Authorization: Bearer {{token}}

### Create a new category
POST http://localhost:3000/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New Category"
}

### Update a category
PATCH http://localhost:3000/categories/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Category Name"
}

### Delete a category
DELETE http://localhost:3000/categories/2
Authorization: Bearer {{token}}

######################### Users Routes #########################

### Get all users
GET http://localhost:3000/users
Authorization: Bearer {{token}}

### Get a user by ID
GET http://localhost:3000/users/by-id/3
Authorization: Bearer {{token}}

### Create a new user
POST http://localhost:3000/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "123456",
  "name": "New User",
  "role": "manager"
}

### Update a user
PATCH http://localhost:3000/users/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "updateduser@example.com",
  "name": "Updated User",
  "password": "newpassword123",
  "role": "manager"
}

### Delete a user
DELETE http://localhost:3000/users/1
Authorization: Bearer {{token}}
